set working-directory := '..'

publish $CARGO_API_TOKEN:
    # Use $CARGO_API_TOKEN rather than {{ CARGO_API_TOKEN }} to avoid
    # printing the token in just output.

    cargo install cargo-release
    cargo release
    # cargo publish --verbose --locked --token $CARGO_API_TOKEN

# Bump the version in Cargo.toml and Cargo.lock, commit the changes, and tag the commit
bump:
    # check that the worktree is clean
    [ -z "$(git status --porcelain)" ]

    cargo install cargo-release
    # Update Cargo.toml and Cargo.lock
    cargo release version patch --execute --no-confirm
    # commit the changes
    cargo release commit --execute --no-confirm
    # tag the commit as 'v{VERSION}'
    cargo release tag --execute --no-confirm

build:
  cargo build --all --verbose

test:
  cargo test --all --verbose
