set working-directory := '..'

publish $CARGO_API_TOKEN:
    # Use $CARGO_API_TOKEN rather than {{ CARGO_API_TOKEN }} to avoid
    # printing the token in just output.

    cargo install cargo-release
    cargo release
    # cargo publish --verbose --locked --token $CARGO_API_TOKEN

# Bump the version in Cargo.toml and Cargo.lock
bump:
    cargo install cargo-release
    # Update Cargo.toml and Cargo.lock
    cargo release version patch --execute --verbose --no-confirm
    # commit the changes
    cargo release commit --execute --verbose --no-confirm


build:
  cargo build --all --verbose

test:
  cargo test --all --verbose
